apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: oper
  labels:
    app: oper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oper
  template:
    metadata:
      labels:
        app: oper
    spec:
      containers:
      - name: oper
        image: calum/operator:test
