apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: aws-operator
  labels:
    app: aws-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-operator
  template:
    metadata:
      labels:
        app: aws-operator
    spec:
      volumes:
      - name: ssl
        hostPath:
          path: /etc/ssl
      - name: awscreds
        hostPath:
          path: $(CREDS_FILE)
      containers:
      - name: aws-operator
        image: teamtrussle/aws-operator:master
        volumeMounts:
        - name: awscreds
          mountPath: /root/.aws/credentials
        - name: ssl
          mountPath: /etc/ssl
