apiVersion: trussle.com/v1alpha1
kind: IamRole
metadata:
  name: my-custom-role
spec:
  name: my-custom-role
  policyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Sid": "Stmt1506946329000",
              "Effect": "Allow",
              "Action": [
            "s3:*"
              ],
              "Resource": [
            "*"
              ]
          }
        ]  
      }
  rolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "ec2.amazonaws.com"
          },
          "Action": "sts:AssumeRole"
        }
      ]
    }
